const hostingUrl = "https://eterna-verde.web.app/";

export const Products: Product[] = [
  {
    id: "epson-powerlite-98h",
    name: "Epson Powerlite 98H",
    oldPrice: 190,
    price: 170,
    stock: 10,
    brand: "epson",
    category: "home",
    size: 150,
    description:
      "Con una conectividad de red avanzada y una calidad de imagen excepcional, el PowerLite 98H ofrece una gran opción para cualquier tipo de sala. La tecnología 3LCD ofrece colores hasta 3x mas brillantes que otros modelos de la competencia. Los proyectores Epson aseguran imágenes brillantes y vívidas. Confiable y fácil de usar, el PowerLite 98H cuanta con una resolución XGA, 3.000 lúmenes de brillo en color y 3.000 lúmenes de brillo en blanco. Proyecte y controle la imagen desde múltiples dispositivos gracias a la nueva función moderador, compartiendo fácilmente el contenido con la audiencia. Versátil y funcional, el PowerLite 98H cuenta con conectividad HDMI y funciones de audio premium.",
    control: true,
    images: [
      "/images/epson98H.jpg",
      "/images/epson98H-2.jpg",
      "/images/epson98H-3.jpg",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/epson-powerlite-98h`,
  },
  {
    id: "epson-powerlite-97h",
    name: "Epson Powerlite 97H",
    oldPrice: 210,
    price: 180,
    stock: 10,
    brand: "epson",
    category: "business",
    size: 120,
    description:
      "Con una conectividad de red avanzada y una calidad de imagen excepcional, el PowerLite 97 ofrece una gran opción para cualquier tipo de salón. La tecnología 3LCD ofrece colores hasta 3x mas brillantes que otros modelos de la competencia. Los proyectores Epson aseguran imágenes brillantes y vívidas. Confiable y fácil de usar, el PowerLite 98 cuanta con una resolución XGA, 2.700 lúmenes de brillo en color y 2.700 lúmenes de brillo en blanco. Proyecte y controle la imagen desde múltiples dispositivos gracias a la nueva función moderador, compartiendo fácilmente el contenido con la audiencia. Versátil y funcional, el PowerLite 97 cuenta con conectividad HDMI y funciones de audio premium.",
    control: true,
    images: [
      "/images/epson97H.jpg",
      "/images/epson97H-2.jpg",
      "/images/epson97H-3.jpg",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/epson-powerlite-97h`,
  },
  {
    id: "epson-powerlite-965H",
    name: "Epson Powerlite 965H",
    oldPrice: 190,
    price: 170,
    stock: 10,
    brand: "epson",
    category: "portable",
    size: 180,
    description:
      "Con conexión de red, imágenes brillantes y una gran conectividad, el PowerLite 965H ofrece la opción perfecta para cualquier tipo de salón. Los proyectores Epson 3LCD ofrecen colores hasta 3x más brillantes que otros modelos de la competencia logrando imágenes naturales y vividas. Confiable y fácil de usar, el PowerLite 965H cuenta con una resolución XGA y 3.500 lúmenes de brillo en color y 3.500 lúmenes de brillo en blanco. Proyecte y controle el contenido desde múltiples dispositivos gracias a la función moderador, compartiendo fácilmente el contenido con el resto de la audiencia. El PowerLite 965H posee un zoom óptico de 1.6x permitiendo una fácil instalación en casi cualquier lugar. Versátil y funcional, el PowerLite 965H cuenta con conectividad HDMI y funciones de audio premium.",
    control: true,
    images: [
      "/images/epson965H.jpg",
      "/images/epson965H-2.jpg",
      "/images/epson965H-3.jpg",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/epson-powerlite-965h`,
  },
  {
    id: "epson-powerlite-e20",
    name: "Epson Powerlite E20",
    oldPrice: 120,
    price: 90,
    stock: 10,
    brand: "epson",
    category: "long-range",
    size: 90,
    description:
      "Obtén una sorprendente proyección en la sala de clases a un precio accesible con el proyector PowerLite E20. Con la avanzada tecnología 3LCD, este proyector ultrabrillante de 3.400-lúmenes1 ofrece imágenes vibrantes y muy reales con el mejor Brillo de Color2 y una resolución nativa XGA. Diseñado específicamente para ambientes de salas de clases, el PowerLite E20 aumenta la participación y enriquece las lecciones con conectividad HDMI® y un altavoz incorporado de 5 W. Construido para durar, este proyector proporciona una larga vida útil de la lámpara de 12.000 horas en Modo ECO3, además de una fácil instalación y flexibilidad de posicionamiento para una fácil proyección desde cualquier lugar de la sala de clases.",
    control: false,
    images: [
      "/images/epsonE20.jpg",
      "/images/epsonE20-2.jpg",
      "/images/epsonE20-3.jpg",
    ],
    link: `${hostingUrl}/products/epson-powerlite-e20`,
  },
  {
    id: "epson-powerlite-x49",
    name: "Epson Powerlite X49",
    oldPrice: 120,
    price: 90,
    stock: 10,
    brand: "epson",
    category: "4k",
    size: 90,
    description:
      "El PowerLite® X49 es el proyector ideal para el segmento de educación. Brinda una pantalla de más de 100 con calidad excepcional. La tecnología 3LCD ofrece imágenes claras, brillantes y llenas de color. Su luminosidad de 3.600 lúmenes en color1 y 3.600 lúmenes en blanco1 lo convierten en la mejor opción para aulas de educación bien iluminadas. Adicionalmente, ofrece una conectividad avanzada con puertos HDMI®, RJ-45 y conectividad inalámbrica opcional4, que permite proyectar el contenido sin requerir cables, perfecto para las aulas escolares actuales.",
    control: false,
    images: [
      "/images/epsonX49.jpg",
      "/images/epsonX49-2.jpg",
      "/images/epsonX49-3.jpg",
    ],
    link: `${hostingUrl}/products/epson-powerlite-x49`,
  },
  {
    id: "epson-powerlite-955wh",
    name: "Epson Powerlite 955WH",
    oldPrice: 100,
    price: 70,
    stock: 10,
    brand: "epson",
    category: "gamer",
    size: 90,
    description:
      "El PowerLite 955WH ofrece excelentes opciones para los salones de hoy incluyendo flexibilidad de instalación y gran conectividad de red. Los proyectores Epson 3LCD ofrecen colores hasta 3x más brillantes que otros modelos de la competencia logrando imágenes naturales y vividas. Con una resolución WXGA de pantalla ancha, el PowerLite 955WH cuenta con 3.200 lúmenes de brillo en color y 3.200 lúmenes de brillo en blanco. Proyecte y controle el contenido desde múltiples dispositivos gracias al la nueva función moderador, compartiendo fácilmente el contenido con la audiencia. El PowerLite 955WH posee un zoom óptico de 1.6x permitiendo una fácil instalación en casi cualquier lugar. El PowerLite 955WH también está equipado con conectividad HDMI y funciones de audio de gran calidad",
    control: false,
    images: [
      "/images/epson955WH.jpg",
      "/images/epson955WH-2.jpg",
      "/images/epson955WH-3.jpg",
    ],
    link: `${hostingUrl}/products/epson-powerlite-955wh`,
  },
  {
    id: "epson-powerlite-990u",
    name: "Epson Powerlite 990U",
    oldPrice: 120,
    price: 90,
    stock: 10,
    brand: "epson",
    category: "business",
    size: 90,
    description:
      "El Epson PowerLite 990U es un proyector de alta resolución diseñado para entornos empresariales y educativos que requieren presentaciones de calidad superior. Ofrece una resolución WUXGA (1920 x 1200), que garantiza imágenes nítidas y detalladas, ideal para mostrar contenido en alta definición. Con un brillo de 3.800 lúmenes, asegura una excelente visibilidad en espacios bien iluminados. Su amplia gama de conectividad, que incluye HDMI y capacidad inalámbrica, permite conectar una variedad de dispositivos fácilmente. Este proyector es perfecto para quienes buscan fiabilidad, claridad y versatilidad en sus presentaciones.",
    control: false,
    images: [
      "/images/epson990U.jpg",
      "/images/epson990U-2.jpg",
      "/images/epson990U-3.jpg",
    ],
    link: `${hostingUrl}/products/epson-powerlite-990u`,
  },
  {
    id: "benq-ms527",
    name: "benQ MS527",
    oldPrice: 130,
    price: 100,
    stock: 10,
    brand: "benq",
    category: "home",
    size: 90,
    description:
      "Proyector BenQ MS527. Con un brillo de 3,300:1 Lúmenes, contraste de 13:000:1 y el Costo-Beneficio del MS527 al ofrecerte una pantalla con detalles finos sin importar el nivel de luz ambiental. Con una proyección optimizada, el ahorro dinámico de energía no compromete el brillo y la calidad de la imagen está asegurada a la perfección gracias a la tecnología SmartEco de BenQ. Con esta innovación, las escuelas y empresas son capaces de ahorrar hasta un 70% del consumo eléctrico de la lámpara y a su vez reduce los costos de mantenimiento a través de funciones de ahorro de energía - mientras experimentas una imagen viva en colores.",
    control: false,
    images: [
      "/images/benQ-MS527.jpg",
      "/images/benQ-MS527-2.jpg",
      "/images/benQ-MS527-3.jpg",
    ],
    link: `${hostingUrl}/products/benq-ms527`,
  },
  {
    id: "benq-mx550",
    name: "benQ MX550",
    oldPrice: 110,
    price: 90,
    stock: 10,
    brand: "benq",
    category: "long-range",
    size: 105,
    description:
      "El proyector MX550 produce un alto brillo de 3,600 lúmenes para mostrar contenido con las luces encendidas en lugares iluminados, el alto brillo garantiza una calidad de imagen con colores vivos junto con una nítida legibilidad de texto. Los proyectores BenQ cuentan con un factor de relleno de pixel, produciendo negros más profundos, esta característica aumenta la claridad de las imágenes y también reduce el cansancio visual. Conectividad múltiple, el proyector MX550 cuenta con 2 entradas HDMI y 2 entradas VGA, las cuales están diseñadas para que múltiples presentadores puedan conectarse sin ningún problema. Estas múltiples entradas permiten que los participantes de la reunión colaboren al instante sin adaptadores y sin el soporte del personal TI.",
    control: false,
    images: [
      "/images/benQ-MX550.jpg",
      "/images/benQ-MX550-2.webp",
      "/images/benQ-MX550-3.jpg",
    ],
    link: `${hostingUrl}/products/benq-mx550`,
  },
  {
    id: "benq-ht2050a",
    name: "benQ HT2050A",
    oldPrice: 110,
    price: 90,
    stock: 10,
    brand: "benq",
    category: "home",
    size: 105,
    description:
      "Calidad de imagen superior: proyector de 1080p con brillo de 2.200 lúmenes, alta relación de contraste nativo y 96% Rec. Calibración de precisión de color 709. Alta sensibilidad: el retraso de entrada baja especializada de 16 ms y modos de juego únicos garantizan a los jugadores una experiencia de juego ultrasuave. Sorprende a tus amigos: toma la acción a la pantalla grande proyectando una pantalla de 100 pulgadas a sólo 8 pies de distancia. Proyecta hasta 300 pulgadas. Conectividad flexible: soporta la mayoría de reproductores multimedia, consolas de juegos, PC, Mac y dispositivos móviles con opciones de entrada como HDMI, USB, y más.",
    control: false,
    images: [
      "/images/benQ-HT2050.webp",
      "/images/benQ-HT2050-2.webp",
      "/images/benQ-HT2050-3.jpg",
    ],
    link: `${hostingUrl}/products/benq-ht2050a`,
  },
  {
    id: "optoma-uhd50x",
    name: "Optoma UHD50X",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "optoma",
    category: "gamer",
    size: 105,
    description:
      "TRUE 4K ULTRA HD: Experimenta una sensación de cine en casa de alta calidad con 4K Ultra HD con 8,3 millones de píxeles direccionables en pantalla distintos. GAMING SIN REGASOS: Presentamos el primer proyector de juegos ultrarrápido de 240Hz del mundo que permite imágenes sin borrosidad y suavidad sin igual, combinado con el modo de juego mejorado para producir un tiempo de respuesta de 16 ms, o 26 ms a 4K UHD para el menor retraso de entrada en un proyector 4K.",
    control: false,
    images: [
      "/images/optomaUHD50X.jpg",
      "/images/optomaUHD50X-2.jpg",
      "/images/optomaUHD50X-3.jpg",
    ],
    link: `${hostingUrl}/products/optoma-uhd50x`,
  },
  {
    id: "optoma-eh412",
    name: "Optoma EH412",
    oldPrice: 180,
    price: 135,
    stock: 10,
    brand: "optoma",
    category: "long-range",
    size: 105,
    description:
      "Proyecta imágenes increíblemente BRILLANTES de 4, 500 lúmenes y 1080P con el Optima EH412. Compatibilidad con fuentes de entrada 4K HDR, serge y rec. 709 perfiles de color con una relación de contraste de 50. 000:1 garantizan imágenes nítidas y vívidas, ideales para aulas, salas de reuniones y formación. El zoom de 1,3 aumentos, la corrección trapezoidal y el control RS232 ofrecen opciones de instalación flexibles. El potente audio de 10 vatios llena la habitación con un sonido alto y nítido para mejorar aún más los medios y las presentaciones. Las entradas robustas incluyen HDMI 2.0 y VGA para conectarse a una amplia gama de dispositivos. La vida útil de la lámpara de 15 000 horas permite muchos años de uso con un mantenimiento mínimo.",
    control: false,
    images: [
      "/images/optomaEH412.jpg",
      "/images/optomaEH412-2.webp",
      "/images/optomaEH412-3.jpg",
    ],
    link: `${hostingUrl}/products/optoma-eh412`,
  },
  {
    id: "optoma-gt1090",
    name: "Optoma GT1090",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "optoma",
    category: "home",
    size: 105,
    description:
      "Lleve la experiencia cinematográfica a entornos con limitaciones de espacio con el increíble proyector láser de corto alcance de 4, 200 lúmenes y 1080p Optoma GT1090HDR. Una relación de proyección corta de 0. 50:1 proyecta increíbles imágenes de 100 pulgadas desde solo varios pies de distancia. Una fuente de luz láser DuraCore elimina los reemplazos de lámpara y filtro durante hasta 30, 000 horas de funcionamiento sin mantenimiento con una calidad de imagen y color asombrosa durante toda la vida útil del proyector. El tamaño compacto y el bajo peso facilitan el montaje, mientras que su funcionamiento silencioso garantiza que la GT1090HDR se vea, no se oiga. La corrección trapezoidal automática y la corrección de cuatro esquinas facilitan el ajuste de la imagen para una fácil instalación. La compatibilidad con Blu-ray 3D lleva a casa la experiencia de las películas 3D envolventes cuando se combina con las gafas 3D DLP-Link opcionales.",
    control: false,
    images: [
      "/images/optomaGT1090.jpeg",
      "/images/optomaGT1090-2.jpg",
      "/images/optomaGT1090-3.jpg",
    ],
    link: `${hostingUrl}/products/optoma-gt1090`,
  },
  {
    id: "optoma-hd146x",
    name: "Optoma HD146X",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "optoma",
    category: "business",
    size: 105,
    description:
      "El proyector Full HD 1080p HD146X es ideal para ver deportes en vivo, programas de televisión o películas en cualquier momento del día. Incluso puede conectar su videoconsola y jugar igual que lo haría en cualquier pantalla gracias a su baja latencia. Cómodo y fácil de configurar, este proyector potente y versátil también cuenta con una tecnología de color asombrosa que ofrece colores brillantes y realistas. Es fácil y cómodo de transportar bolsa de transporte opcional, ya sea para un evento deportivo, una noche de cine o un maratón de juegos disfrutando así de la mejor experiencia de pantalla grande en cualquier lugar con una superficie plana.",
    control: false,
    images: [
      "/images/optomaHD146X.webp",
      "/images/optomaHD146X-2.jpg",
      "/images/optomaHD146X-3.webp",
    ],
    link: `${hostingUrl}/products/optoma-hd146x`,
  },
  {
    id: "optoma-zh406",
    name: "Optoma ZH406",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "optoma",
    category: "business",
    size: 105,
    description:
      "El proyector Full HD 1080p HD146X es ideal para ver deportes en vivo, programas de televisión o películas en cualquier momento del día. Incluso puede conectar su videoconsola y jugar igual que lo haría en cualquier pantalla gracias a su baja latencia. Cómodo y fácil de configurar, este proyector potente y versátil también cuenta con una tecnología de color asombrosa que ofrece colores brillantes y realistas. Es fácil y cómodo de transportar bolsa de transporte opcional, ya sea para un evento deportivo, una noche de cine o un maratón de juegos disfrutando así de la mejor experiencia de pantalla grande en cualquier lugar con una superficie plana.",
    control: false,
    images: [
      "/images/optomaZH406.jpg",
      "/images/optomaZH406-2.webp",
      "/images/optomaZH406-3.webp",
    ],
    link: `${hostingUrl}/products/optoma-zh406`,
  },
  {
    id: "sony-gtz380",
    name: "Sony GTZ380",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "sony",
    category: "portable",
    size: 105,
    description:
      "El VPL-GTZ380 muestra fielmente imágenes con resolución 4K nativa (4096 x 2160), sin necesidad de la conversión de señal ni los trucos de desplazamiento de píxeles que se utilizan en proyectores de menor tamaño. Los detalles más pequeños son increíblemente nítidos y claros, incluso cuando el público está más cerca de la pantalla en entornos como salas de exposiciones corporativas y vestíbulos.",
    control: false,
    images: [
      "/images/sonyGTZ380.webp",
      "/images/sonyGTZ380-2.png",
      "/images/sonyGTZ380-3.jpg",
    ],
    link: `${hostingUrl}/products/sony-gtz380`,
  },
  {
    id: "sony-hw45es",
    name: "Sony HW45ES",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "sony",
    category: "4k",
    size: 105,
    description:
      "Crea una experiencia cinematográfica espectacular en tu propia casa. El VPL-HW45ES está repleto de tecnología desarrollada para nuestros proyectores profesionales de cine digital, incluidos paneles SXRD y tecnología de ampliación de creación de realidad avanzada para imágenes Full HD fabulosamente detalladas. Con un brillo de 1.800 lúmenes y un diseño compacto, es la elección perfecta para un entretenimiento en casa inolvidable. Fuente de luz: Lámpara de mercurio de alta presión, tipo 215 W.",
    control: false,
    images: [
      "/images/sonyHW45ES.webp",
      "/images/sonyHW45ES-2.jpg",
      "/images/sonyHW45ES-3.jpg",
    ],
    link: `${hostingUrl}/products/sony-hw45es`,
  },
  {
    id: "sony-phz10",
    name: "Sony PHZ10",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "sony",
    category: "long-range",
    size: 105,
    description:
      "Sony VPL-PHZ10-Proyector LCD 5000 lúmenes-1920x1200-16:10-HD-LAN-Laser Led Fósforo-Contraste de 500000:1. Gracias a su diseño elegante y discreto,además del bajo nivel de ruido del ventilador,el VPL-PHZ10 se adapta a la perfección a casi cualquier espacio:desde instituciones académicas hasta entornos empresariales. Instala el proyector en cualquier ángulo,incluso de lado o boca abajo. Ahora configurar la unidad es más fácil que nunca gracias al intuitivo menú de instalación.",
    control: false,
    images: [
      "/images/sonyPHZ10.jpeg",
      "/images/sonyPHZ10-2.jpeg",
      "/images/sonyPHZ10-3.jpg",
    ],
    link: `${hostingUrl}/products/sony-phz10`,
  },
  {
    id: "sony-vw295es",
    name: "Sony VW295ES",
    oldPrice: 160,
    price: 125,
    stock: 10,
    brand: "sony",
    category: "gamer",
    size: 105,
    description:
      "Lleva el cine a tu hogar con el Sony VPL-VW295ES, un proyector 4K HDR que combina tecnología avanzada y diseño elegante. Con resolución 4096 x 2160 píxeles, compatibilidad con HDR10 y HLG, y tecnología SXRD, ofrece colores vibrantes, negros profundos y detalles impresionantes. El procesador X1 optimiza cada fotograma, mientras que su relación de contraste de 350,000:1 y brillo de 1,500 lúmenes garantizan imágenes nítidas y brillantes. Incluye ajustes de lente óptica, dos puertos HDMI 4K/60Hz y operación silenciosa (26 dB), ideal para salas de cualquier tamaño. Perfecto para cineastas exigentes y amantes del entretenimiento.",
    control: false,
    images: [
      "/images/sonyVW295ES.jpg",
      "/images/sonyVW295ES-2.jpg",
      "/images/sonyVW295ES-3.webp",
    ],
    link: `${hostingUrl}/products/sony-vw295es`,
  },
];
