export const Products: Product[] = [
  {
    id: "platanera-artificial-150-cm",
    name: "Platanera Artificial 150 cm",
    oldPrice: 190,
    price: 170,
    stock: 10,
    size: "150 cm",
    maceta: true,
    images: [
      "/images/platanero.webp",
      "/images/platanero-2.webp",
      "/images/platanero-3.webp",
      "/images/platanero-4.webp",
    ],
    isBestSeller: true,
  },
  {
    id: "dracena-artificial-120-cm",
    name: "Drácena Artificial 120 cm",
    oldPrice: 210,
    price: 180,
    stock: 10,
    size: "120 cm",
    maceta: true,
    images: [
      "/images/dracena.webp",
      "/images/dracena-2.webp",
      "/images/dracena-3.webp",
    ],
    isBestSeller: true,
  },
  {
    id: "ficus-artificial-180-cm",
    name: "Ficus Artificial 180 cm",
    oldPrice: 190,
    price: 170,
    stock: 10,
    size: "180 cm",
    maceta: true,
    images: [
      "/images/ficus.webp",
      "/images/ficus-2.webp",
      "/images/ficus-3.webp",
    ],
    isBestSeller: true,
  },
  {
    id: "ficus-elastica-90.webp",
    name: "Ficus elastica 90 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "90 cm",
    maceta: false,
    images: [
      "/images/ficus-elastica-90.webp",
      "/images/ficus-elastica-90-2.webp",
      "/images/ficus-elastica-90-3.webp",
    ],
  },
  {
    id: "palmera-165",
    name: "Palmera 165 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "90 cm",
    maceta: false,
    images: [
      "/images/palmera-165.webp",
      "/images/palmera-165-2.webp",
      "/images/palmera-165-3.webp",
    ],
  },
  {
    id: "colgante-artificial",
    name: "Colgante artificial",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "90 cm",
    maceta: false,
    images: ["/images/colgante-artificial.webp"],
  },
  {
    id: "colgante-artificial-de-helecho",
    name: "Colgante artificial de helecho",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "90 cm",
    maceta: false,
    images: [
      "/images/colgante-artificial-de-helecho.webp",
      "/images/colgante-artificial-de-helecho-2.webp",
    ],
  },
  {
    id: "monstera-artificial-160",
    name: "Monstera artificial 160 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "90 cm",
    maceta: false,
    images: [
      "/images/monstera-artificial-160.webp",
      "/images/monstera-artificial-160-2.webp",
      "/images/monstera-artificial-160-3.webp",
      "/images/monstera-artificial-160-4.webp",
    ],
  },
  {
    id: "dracena-artificial-105",
    name: "Drácena artificial 105 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "105 cm",
    maceta: false,
    images: [
      "/images/dracena-artificial-105.webp",
      "/images/dracena-artificial-105-2.webp",
      "/images/dracena-artificial-105-3.webp",
    ],
  },
  {
    id: "bambu-artificial-minimal-210",
    name: "Bambu artificial minimal 210 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "210 cm",
    maceta: false,
    images: [
      "/images/bambu-artificial-minimal-210.webp",
      "/images/bambu-artificial-minimal-210-2.webp",
      "/images/bambu-artificial-minimal-210-3.webp",
      "/images/bambu-artificial-minimal-210-4.webp",
    ],
  },
  {
    id: "eucalipto-artificial-105",
    name: "Eucalipto artificial 105 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "105 cm",
    maceta: false,
    images: [
      "/images/eucalipto-artificial-105.webp",
      "/images/eucalipto-artificial-105-2.webp",
      "/images/eucalipto-artificial-105-3.webp",
      "/images/eucalipto-artificial-105-4.webp",
    ],
  },
  {
    id: "almendro-artificial-180",
    name: "Almendro artificial 180 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "180 cm",
    maceta: false,
    images: [
      "/images/almendro-artificial-180.webp",
      "/images/almendro-artificial-180-2.webp",
      "/images/almendro-artificial-180-3.webp",
      "/images/almendro-artificial-180-4.webp",
    ],
  },
  {
    id: "ave-paraiso-artificial-210",
    name: "Ave paraiso artificial 210 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: "210 cm",
    maceta: false,
    images: [
      "/images/ave-paraiso-artificial-210.webp",
      "/images/ave-paraiso-artificial-210-2.webp",
      "/images/ave-paraiso-artificial-210-3.webp",
    ],
  },
  {
    id: "sakura-mini-rojo",
    name: "Sakura mini rojo",
    oldPrice: 80,
    price: 70,
    stock: 10,
    size: "100 cm",
    maceta: true,
    images: ["/images/sakura-rojo.jpg", "/images/sakura-rojo-2.jpg"],
  },
  {
    id: "sakura-mini-rosado",
    name: "Sakura mini rosado",
    oldPrice: 80,
    price: 70,
    stock: 10,
    size: "100 cm",
    maceta: false,
    images: ["/images/sakura-rosa.jpg", "/images/sakura-rosa-2.jpg"],
  },
];
