const hostingUrl = "https://eterna-verde.web.app/";

export const Products: Product[] = [
  {
    id: "platanera-artificial-150-cm",
    name: "Platanera Artificial 150 cm",
    oldPrice: 190,
    price: 170,
    stock: 10,
    size: 150,
    maceta: true,
    images: [
      "/images/platanero.webp",
      "/images/platanero-2.webp",
      "/images/platanero-3.webp",
      "/images/platanero-4.webp",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/platanera-artificial-150-cmplatanera-artificial-150-cm`,
  },
  {
    id: "dracena-artificial-120-cm",
    name: "Drácena Artificial 120 cm",
    oldPrice: 210,
    price: 180,
    stock: 10,
    size: 120,
    maceta: true,
    images: [
      "/images/dracena.webp",
      "/images/dracena-2.webp",
      "/images/dracena-3.webp",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/dracena-artificial-120-cm`,
  },
  {
    id: "ficus-artificial-180-cm",
    name: "Ficus Artificial 180 cm",
    oldPrice: 190,
    price: 170,
    stock: 10,
    size: 180,
    maceta: true,
    images: [
      "/images/ficus.webp",
      "/images/ficus-2.webp",
      "/images/ficus-3.webp",
    ],
    isBestSeller: true,
    link: `${hostingUrl}/products/ficus-artificial-180-cm`,
  },
  {
    id: "ficus-elastica-90",
    name: "Ficus elastica 90 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: 90,
    maceta: false,
    images: [
      "/images/ficus-elastica-90.webp",
      "/images/ficus-elastica-90-2.webp",
      "/images/ficus-elastica-90-3.webp",
    ],
    link: `${hostingUrl}/products/ficus-elastica-90`,
  },
  {
    id: "palmera-165",
    name: "Palmera 165 cm",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: 90,
    maceta: false,
    images: [
      "/images/palmera-165.webp",
      "/images/palmera-165-2.webp",
      "/images/palmera-165-3.webp",
    ],
    link: `${hostingUrl}/products/palmera-165`,
  },
  {
    id: "colgante-artificial",
    name: "Colgante artificial",
    oldPrice: 100,
    price: 70,
    stock: 10,
    size: 90,
    maceta: false,
    images: ["/images/colgante-artificial.webp"],
    link: `${hostingUrl}/products/colgante-artificial`,
  },
  {
    id: "colgante-artificial-de-helecho",
    name: "Colgante artificial de helecho",
    oldPrice: 120,
    price: 90,
    stock: 10,
    size: 90,
    maceta: false,
    images: [
      "/images/colgante-artificial-de-helecho.webp",
      "/images/colgante-artificial-de-helecho-2.webp",
    ],
    link: `${hostingUrl}/products/colgante-artificial-de-helecho`,
  },
  {
    id: "monstera-artificial-160",
    name: "Monstera artificial 160 cm",
    oldPrice: 130,
    price: 100,
    stock: 10,
    size: 90,
    maceta: false,
    images: [
      "/images/monstera-artificial-160.webp",
      "/images/monstera-artificial-160-2.webp",
      "/images/monstera-artificial-160-3.webp",
      "/images/monstera-artificial-160-4.webp",
    ],
    link: `${hostingUrl}/products/monstera-artificial-160`,
  },
  {
    id: "dracena-artificial-105",
    name: "Drácena artificial 105 cm",
    oldPrice: 110,
    price: 90,
    stock: 10,
    size: 105,
    maceta: false,
    images: [
      "/images/dracena-artificial-105.webp",
      "/images/dracena-artificial-105-2.webp",
      "/images/dracena-artificial-105-3.webp",
    ],
    link: `${hostingUrl}/products/dracena-artificial-105`,
  },
  {
    id: "bambu-artificial-minimal-210",
    name: "Bambu artificial minimal 210 cm",
    oldPrice: 140,
    price: 110,
    stock: 10,
    size: 210,
    maceta: false,
    images: [
      "/images/bambu-artificial-minimal-210.webp",
      "/images/bambu-artificial-minimal-210-2.webp",
      "/images/bambu-artificial-minimal-210-3.webp",
      "/images/bambu-artificial-minimal-210-4.webp",
    ],
    link: `${hostingUrl}/products/bambu-artificial-minimal-210`,
  },
  {
    id: "eucalipto-artificial-105",
    name: "Eucalipto artificial 105 cm",
    oldPrice: 100,
    price: 80,
    stock: 10,
    size: 105,
    maceta: false,
    images: [
      "/images/eucalipto-artificial-105.webp",
      "/images/eucalipto-artificial-105-2.webp",
      "/images/eucalipto-artificial-105-3.webp",
      "/images/eucalipto-artificial-105-4.webp",
    ],
    link: `${hostingUrl}/products/eucalipto-artificial-105`,
  },
  {
    id: "almendro-artificial-180",
    name: "Almendro artificial 180 cm",
    oldPrice: 150,
    price: 120,
    stock: 10,
    size: 180,
    maceta: false,
    images: [
      "/images/almendro-artificial-180.webp",
      "/images/almendro-artificial-180-2.webp",
      "/images/almendro-artificial-180-3.webp",
      "/images/almendro-artificial-180-4.webp",
    ],
    link: `${hostingUrl}/products/almendro-artificial-180`,
  },
  {
    id: "ave-paraiso-artificial-210",
    name: "Ave paraiso artificial 210 cm",
    oldPrice: 140,
    price: 110,
    stock: 10,
    size: 210,
    maceta: false,
    images: [
      "/images/ave-paraiso-artificial-210.webp",
      "/images/ave-paraiso-artificial-210-2.webp",
      "/images/ave-paraiso-artificial-210-3.webp",
    ],
    link: `${hostingUrl}/products/ave-paraiso-artificial-210`,
  },
  {
    id: "sakura-mini-rojo",
    name: "Sakura mini rojo",
    oldPrice: 160,
    price: 140,
    stock: 10,
    size: 100,
    maceta: true,
    images: ["/images/sakura-rojo.jpg", "/images/sakura-rojo-2.jpg"],
    link: `${hostingUrl}/products/sakura-mini-rojo`,
  },
  {
    id: "sakura-mini-rosado",
    name: "Sakura mini rosado",
    oldPrice: 160,
    price: 140,
    stock: 10,
    size: 100,
    maceta: false,
    images: ["/images/sakura-rosa.jpg", "/images/sakura-rosa-2.jpg"],
    link: `${hostingUrl}/products/sakura-mini-rosado`,
  },
];
